apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook
data:
  config: |
    [osd]
    cluster network = 10.233.64.0/18
    cluster addr = 0.0.0.0
    public network = 10.233.64.0/18
